#!/usr/bin/env bash
# Bash
sudo apt update
sudo apt -y install nginx
echo 'Hello World' > index.html
sudo mv index.html /var/www/html/
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
