#!/usr/bin/env bash
# Sets up an nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}" /etc/nginx/sites-available/default
service nginx start

