#!/usr/bin/env bash
#to configure a new server

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart


