#!/usr/bin/env bash
# Configure a HAproxy load-balancer
sudo apt -y update
sudo apt -y upgrade
sudo apt-get install -y haproxy
sudo sed -i "$ a\ENABLED=1" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\ \tlisten jorgecal \n\tmode http\n\tbind *:80\n\tbalance roundrobin\n\tserver 3821-web-01 54.226.20.179:80 check\n\tserver 3821-web-02 3.89.59.76:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
