#!/usr/bin/env bash
# Configure a HAproxy load-balancer
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 3821-web-01 54.226.20.179:80 check\n\tserver 3821-web-02 3.89.59.76:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
